name: Skip Redundant Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  skip-check:
    name: Check if we should skip workflows
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should-skip }}
      paths-result: ${{ steps.skip-check.outputs.paths-result }}
      
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/*.md", "docs/**", "*.txt"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'
          
  conditional-workflows:
    name: Trigger conditional workflows
    needs: skip-check
    runs-on: ubuntu-latest
    if: needs.skip-check.outputs.should-skip != 'true'
    
    steps:
      - name: Log workflow execution
        run: |
          echo "Running workflows for changes in: ${{ needs.skip-check.outputs.paths-result }}"
          echo "Should skip: ${{ needs.skip-check.outputs.should-skip }}"