name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
      changelog_type:
        description: 'Type of changes'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      description:
        description: 'Description of changes'
        required: true
        type: string

jobs:
  version-bump:
    name: Create Version Bump PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install package dependencies
        run: npm ci
        working-directory: ./packages/authentication
        
      - name: Install changesets
        run: npm install @changesets/cli
        
      - name: Create changeset
        run: |
          cat > .changeset/$(date +%s).md << EOF
          ---
          "@xala-technologies/authentication": ${{ github.event.inputs.changelog_type }}
          ---
          
          ${{ github.event.inputs.description }}
          EOF
          
      - name: Run tests before version bump
        run: |
          cd packages/authentication
          npm run test:all || echo "Tests failed - proceeding with caution"
          
      - name: Generate version bump
        run: |
          cd packages/authentication
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          
      - name: Update changelog
        run: |
          cd packages/authentication
          npx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          
      - name: Update package metadata
        run: |
          cd packages/authentication
          # Update package.json with new metadata
          npm pkg set publishConfig.access=public
          npm pkg set repository.type=git
          npm pkg set repository.url="https://github.com/xala-technologies/authentication.git"
          npm pkg set repository.directory="packages/authentication"
          npm pkg set bugs.url="https://github.com/xala-technologies/authentication/issues"
          npm pkg set homepage="https://github.com/xala-technologies/authentication#readme"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ github.event.inputs.version_type }}"
          title: "chore: version bump (${{ github.event.inputs.version_type }})"
          body: |
            ## Version Bump: ${{ github.event.inputs.version_type }}
            
            ### Changes
            ${{ github.event.inputs.description }}
            
            ### Type of Change
            - ${{ github.event.inputs.changelog_type }} change
            
            ### Automated Updates
            - [x] Version bumped in package.json
            - [x] Changelog updated
            - [x] Package metadata updated
            - [x] Changeset created
            
            ### Pre-release Checklist
            - [ ] Tests passing
            - [ ] Documentation updated
            - [ ] Security audit clean
            - [ ] Compliance checks passed
            - [ ] Performance benchmarks acceptable
            
            ### Post-merge Actions
            After merging this PR, the changeset workflow will:
            1. Create a release PR with final changes
            2. Publish to npm registry
            3. Create GitHub release with notes
            4. Update project documentation
            
            ---
            
            *This PR was automatically created by the Version Bump workflow*
          branch: version-bump-${{ github.event.inputs.version_type }}
          delete-branch: true
          draft: false